### ISSUE TITLE
Provide a regex to allow for vanilla URLs to be parsed

### ISSUE THREAD

**Issue by DesignByOnyx** [disintegrator/gulp-buster#3]
I understand the decision behind the `ASSET { ... }` wrapper - forcing users to be very explicit about which URLs get processed. But it would be nice if you provided a regex that people could copy and paste that would match all URLs defined in CSS, script, link, and img tags. I took the time to write one, as it wasn't the easiest thing:  

``` js
(?:url\(|<(?:link|script|img)[^>]+(?:src|href)\s*=\s*)(?!['"]?(?:data|http))['"]?([^'"\)\s>]+)
```

This works on the following, not matching any remote URLs or DATA urls:

http://www.regexpal.com/?fam=94254

``` css
{
  background-image: url("foo/bar.jpg");
  background: url(data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7);
  background: url("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7");
  background-image: no-repeat url(/asdf/foo/bar.jpg);
  background: transparent no-repeat url(/asdf/foo/bar.jpg) top left;
  list-style: square url("/asdf/foo/bar.jpg");
  content: url("/asdf/foo/bar.jpg");
  background-image: url(http://remote.com/asdf/foo/bar.jpg);
  background-image: url("http://remote.com/asdf/foo/bar.jpg");
}
```

``` html
<link rel="stylesheet" href="/asdf/foo/bar.jpg" />
<link rel="stylesheet" href="http://remote.com/asdf/foo/bar.jpg" />
<script src="https://cdn.mysite.com/assets/scripts/vendor.min.js.gz"></script>
<script type="text/javascript" src='/asdf/foo/bar.jpg'></script>
<img alt="foo" src=/asdf/foo/bar.jpg>
<img alt="foo" src=/asdf/foo/bar.jpg />
<img src=https://cdn.mysite.com/assets/scripts/vendor.min.js.gz />
<img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" />
```
